crudFirst/Models/class1.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace crudFirst.Models
{
    public class class1
    {

        public int id { get; set; }

        public string name { get; set; }
        public string email { get; set; }
        public string DOB { get; set; }
        public string address { get; set; }
    }
}

crudFirst/Controllers/HomeController.cs
using crudFirst.DB_context;
using crudFirst.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace crudFirst.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            studentEntities obj = new studentEntities();
            List<class1 >obj1 = new List<class1>();


            var res = obj.student_tbl.ToList();

            foreach (var item in res)
            {
                obj1.Add(new class1
                {

                    id = item.id, 
                    name= item.name,
                    email=item.email,
                    DOB=item.DOB,
                    address=item.address




                }); 
                
            }

            return View(obj1);
        }

      
    }
}

crudFirst/Controllers/postController.cs
using crudFirst.DB_context;
using crudFirst.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace crudFirst.Controllers
{
    public class postController : Controller
    {
        studentEntities obj = new studentEntities();
        student_tbl objnew = new student_tbl();

        // GET: post

        [HttpGet]

        public ActionResult Adddata()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Adddata(class1 obj1)
        {
           
            objnew.id = obj1.id;
            objnew.name = obj1.name;
            objnew.email = obj1.email;
            objnew.DOB = obj1.DOB;
            objnew.address = obj1.address;

            obj.student_tbl.Add(objnew);
            obj.SaveChanges();
            return View();
        }
    }
}

crudFirst/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<form>
    <div class="form-group">
        <label for="exampleInputEmail1">Name</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Dob</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

crudFirst/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

crudFirst/Views/Home/Index.cshtml
@model List<crudFirst.Models.class1>

@{
    ViewBag.Title = "Home Page";


}

<link href="~/Content/css.css" rel="stylesheet" />


<br>
<h1>Student's Data </h1>

<table class="table table-hover table-bordered  table-responsive table-secondary">
    <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>EMAIL</th>
        <th>DOB</th>
        <th>ADDRESS</th>
        <th>Edit / Delete</th>
    </tr>


    @foreach (var item in Model)
    {
        <tr class="table-active ">
            <td>@item.id</td>
            <td>@item.name</td>
            <td>@item.email</td>
            <td> @item.DOB</td>
            <td>@item.address</td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <span class="badge bg-primary">Edit</span>
                    <span class="badge bg-light">Delete</span>
            </td>

        </tr>


    }
    

</table>
<tr>
    <button type="button" class="btn btn-success">Submit</button>
    <button type="button" class="btn btn-primary">Clear</button>
</tr>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

crudFirst/Views/Home/adddata.cshtml
@model crudFirst.Models.class1
@{
    ViewBag.Title = "Adddata";
}

<link href="~/Content/css.css" rel="stylesheet" />

@using (Html.BeginForm("Adddata", "post", FormMethod.Post))
{


<br>
<h1>Add New Record ...</h1>
<br>
<div class="form-group">
    <label>Name</label>
    @Html.TextBoxFor(m => m.name, new { @class = "form-control", @placeholder = "Name" , @required="required" })


</div>
<div class="form-group">
    <label>Email</label>
    @Html.TextBoxFor(m => m.email, new { @class = "form-control", @placeholder = "Email", @required = "required" })


</div>
<div class="form-group">
    <label>Dob</label>
    @Html.TextBoxFor(m => m.DOB, new { @class = "form-control", @placeholder = "Date of birth", @required = "required" })


</div>
<div class="form-group">
    <label>Address</label>
    @Html.TextBoxFor(m => m.address, new { @class = "form-control", @placeholder = "Address", @required = "required" })


</div>
<button type="submit" class="btn btn-success">Submit</button>}

crudFirst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg ">
        <div class="container-fluid">
           
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav me-auto">
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            @*<li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                            <li>@Html.ActionLink("Add", "Adddata", "Home")</li>
                        </ul>
                    </div>

                  
                </ul>
                <form class="d-flex">
                    <input class="form-control me-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
        <hr>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fazal Mahfooz </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

crudFirst/Views/post/Adddata.cshtml
@model crudFirst.Models.class1
@{
    ViewBag.Title = "Adddata";
}

<link href="~/Content/css.css" rel="stylesheet" />



@using (Html.BeginForm("Adddata", "post", FormMethod.Post))
{
    <br>
    <br>
    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(m => m.name, new { @class = "form-control", @placeholder = "Name", @required = "required" })


    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(m => m.email, new { @class = "form-control", @placeholder = "Email", @required = "required" })


    </div>
    <div class="form-group">
        <label>Dob</label>
        @Html.TextBoxFor(m => m.DOB, new { @class = "form-control", @placeholder = "Date of birth", @required = "required" })


    </div>
    <div class="form-group">
        <label>Address</label>
        @Html.TextBoxFor(m => m.address, new { @class = "form-control", @placeholder = "Address", @required = "required" })


    </div>
    <button type="submit" class="btn btn-success">Submit</button>
}